{
  "hash": "b238dfc04faeb34ad9a66e9a6d8b7d13",
  "result": {
    "engine": "knitr",
    "markdown": "---\noutput: html_document\neditor_options: \n  chunk_output_type: console\n---\n\n## Estratégias de Cross-Selling em Mercado\n\n\n\n\nComo os supermercados e e-commerces decidem o layout das gôndolas ou as recomendações de \"compre junto\"? Vamos utilizar o algoritmo Apriori para minerar associações e entender o trade-off entre volume e especificidade. Em um mar de milhares de regras, como identificar aquelas que são estatisticamente robustas e comercialmente relevantes?\n\n### Terminologia de Regras de Associação {.unnumbered}\n\nAo trabalhar com arules, nosso foco está em três métricas que definem a qualidade da nossa \"entrega\":\n\n- Antecedente ($X$): O produto que já está no carrinho do cliente.\n- Consequente ($Y$): O produto que queremos oferecer (o \"próximo passo\").\n- Suporte: Qual a penetração dessa combinação no faturamento total? (É um nicho ou é massa?)\n- Confiança: Se o cliente comprou $X$, qual a probabilidade real de ele aceitar $Y$?\n- Lift: O quanto a oferta de $X$ impulsiona $Y$ para além da venda natural do produto?\n\n## O cenário e os dados\n\nVamos analisar o dataset `Groceries`. Imagine que você é o Category Manager de uma rede de supermercados e precisa decidir quais produtos colocar em promoção conjunta.\n\nDiferente de modelos de regressão, aqui trabalhamos com objetos de classe transactions (matrizes esparsas), otimizados para grandes volumes de itens.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(arules)\nlibrary(dplyr)\n\n\ndata(Groceries)\n```\n:::\n\n\n\n### Diagnóstico da Operação {.unnumbered}\nAntes de rodar o algoritmo, precisamos entender o comportamento da base:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(Groceries)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntransactions as itemMatrix in sparse format with\n 9835 rows (elements/itemsets/transactions) and\n 169 columns (items) and a density of 0.02609146 \n\nmost frequent items:\n      whole milk other vegetables       rolls/buns             soda \n            2513             1903             1809             1715 \n          yogurt          (Other) \n            1372            34055 \n\nelement (itemset/transaction) length distribution:\nsizes\n   1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16 \n2159 1643 1299 1005  855  645  545  438  350  246  182  117   78   77   55   46 \n  17   18   19   20   21   22   23   24   26   27   28   29   32 \n  29   14   14    9   11    4    6    1    1    1    1    3    1 \n\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   2.000   3.000   4.409   6.000  32.000 \n\nincludes extended item information - examples:\n       labels  level2           level1\n1 frankfurter sausage meat and sausage\n2     sausage sausage meat and sausage\n3  liver loaf sausage meat and sausage\n```\n\n\n:::\n:::\n\n\nNote que, com 9.835 transações registradas e 169 itens distintos, podemos observar uma densidade de aproximadamente 0.026, indicando que o conjunto de dados é relativamente esparsamente povoado. \nAlém disso, os itens mais frequentemente comprados incluem leite integral, vegetais diversos, pães, refrigerantes e iogurte, com quantidades significativamente maiores em comparação com outros itens. \nTambém, a distribuição do comprimento dos itens mostra que a maioria das transações contém entre 1 e 6 itens, com uma mediana de 3 itens por transação. Isso sugere que os clientes geralmente compram um pequeno número de itens por vez. \n\n::: {.callout-tip collapse=\"false\" title=\"O Desafio\"}\nVender leite é fácil (alta frequência). O lucro real está em descobrir quais itens de nicho \"puxam\" outros itens de maior margem.\n:::\n\n## O algoritmo _apriori_\n\n\nO algoritmo *Apriori* é um método popular para mineração de regras de associação em conjuntos de dados. \nEle opera em duas etapas principais: primeiro, **identifica** todos os conjuntos de itens frequentes, ou seja, aqueles que aparecem com uma frequência maior que um limite pré-definido (suporte mínimo). \nEm seguida, com base nesses conjuntos frequentes, **gera regras** de associação, que são implicações do tipo \"se $X$, então $Y$\", onde $X$ e $Y$ são conjuntos de itens, calculando medidas como _confiança_ e _lift_ para avaliar a força das associações entre os itens.\n\nA _confiança_ de uma regra é a probabilidade condicional de que um item (ou conjunto de itens) $Y$ seja comprado, dado que o item (ou conjunto de itens) $X$ também foi comprado. \nEm outras palavras, é a proporção de transações que contêm tanto $X$ quanto $Y$, em relação ao número de transações que contêm $X$. \nUma alta confiança indica que o item $Y$ é frequentemente comprado quando o item $X$ é comprado, o que sugere uma forte associação entre eles.\n\nO _lift_ de uma regra é uma medida de quão mais frequentemente $X$ e $Y$ ocorrem juntos do que seria esperado se fossem independentes. \nEm termos simples, o lift é a razão entre a confiança da regra e a frequência absoluta de $Y$. \nUm lift maior que 1 indica que a regra tem uma associação positiva (os itens ocorrem juntos com mais frequência do que o esperado ao acaso), enquanto um lift menor que 1 indica uma associação negativa (os itens ocorrem juntos com menos frequência do que o esperado ao acaso).\n\nNão queremos todas as regras possíveis (seriam milhões). Precisamos filtrar aquelas que têm relevância estatística e potencial de negócio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Gerando regras: Queremos algo que aconteça em pelo menos 0.1% das vendas\n# e que tenha pelo menos 80% de chance de acontecer (Confiança)\nrules <- apriori(Groceries, parameter = list(sup = 0.001, conf = 0.8))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nApriori\n\nParameter specification:\n confidence minval smax arem  aval originalSupport maxtime support minlen\n        0.8    0.1    1 none FALSE            TRUE       5   0.001      1\n maxlen target  ext\n     10  rules TRUE\n\nAlgorithmic control:\n filter tree heap memopt load sort verbose\n    0.1 TRUE TRUE  FALSE TRUE    2    TRUE\n\nAbsolute minimum support count: 9 \n\nset item appearances ...[0 item(s)] done [0.00s].\nset transactions ...[169 item(s), 9835 transaction(s)] done [0.00s].\nsorting and recoding items ... [157 item(s)] done [0.00s].\ncreating transaction tree ... done [0.00s].\nchecking subsets of size 1 2 3 4 5 6 done [0.01s].\nwriting ... [410 rule(s)] done [0.00s].\ncreating S4 object  ... done [0.00s].\n```\n\n\n:::\n:::\n\n\nO código abaixo exibe os cinco primeiros conjuntos de regras de associação descobertos pelo algoritmo Apriori. \nEle mostra as associações entre os itens, juntamente com suas medidas de suporte, confiança e lift.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspect(rules[1:5])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    lhs                         rhs            support     confidence\n[1] {liquor, red/blush wine} => {bottled beer} 0.001931876 0.9047619 \n[2] {curd, cereals}          => {whole milk}   0.001016777 0.9090909 \n[3] {yogurt, cereals}        => {whole milk}   0.001728521 0.8095238 \n[4] {butter, jam}            => {whole milk}   0.001016777 0.8333333 \n[5] {soups, bottled beer}    => {whole milk}   0.001118454 0.9166667 \n    coverage    lift      count\n[1] 0.002135231 11.235269 19   \n[2] 0.001118454  3.557863 10   \n[3] 0.002135231  3.168192 17   \n[4] 0.001220132  3.261374 10   \n[5] 0.001220132  3.587512 11   \n```\n\n\n:::\n:::\n\n\nCada regra é apresentada acima com os itens à esquerda (`lhs`) e os itens à direita (`rhs`), indicando a associação entre eles. A coluna \"support\" indica a frequência relativa da ocorrência da regra no conjunto de dados, enquanto a coluna \"confidence\" mostra a probabilidade condicional de que os itens à direita da regra sejam comprados, dado que os itens à esquerda foram comprados. O \"lift\" é uma medida da força da associação entre os itens, indicando quantas vezes mais provável é a compra dos itens à direita da regra em comparação com sua compra independente.\n\n\n## Visualizando o Dilema: Confiança vs. Lift\n\nNo negócio, existe um trade-off:\n\n- **Regras de Alta Confiança**: São óbvias (ex: quem compra pão, compra manteiga). O risco de errar é baixo, mas o valor agregado da sugestão também pode ser baixo.\n\n- **Regras de Alto Lift**: São as \"minas de ouro\". Elas mostram associações surpreendentes que a intuição humana geralmente não percebe.\n\n\n### Top 5: As Regras \"Certeiras\" (Alta Confiança) {.unnumbered}\n\nNo código abaixo, estamos extraindo as cinco primeiras regras com base na confiança mais alta. Isso nos permite identificar as associações mais fortes entre os itens, onde a confiança é uma medida da probabilidade de que o item B seja comprado quando o item A é comprado. Todas as cinco regras apresentam uma confiança de 100%, o que indica que sempre que os itens à esquerda da regra são comprados, os itens à direita também são comprados. Isso sugere que essas combinações de itens são altamente associadas no conjunto de dados.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspect(head(rules, n = 5, by = \"confidence\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    lhs                      rhs              support confidence    coverage     lift count\n[1] {rice,                                                                                 \n     sugar}               => {whole milk} 0.001220132          1 0.001220132 3.913649    12\n[2] {canned fish,                                                                          \n     hygiene articles}    => {whole milk} 0.001118454          1 0.001118454 3.913649    11\n[3] {root vegetables,                                                                      \n     butter,                                                                               \n     rice}                => {whole milk} 0.001016777          1 0.001016777 3.913649    10\n[4] {root vegetables,                                                                      \n     whipped/sour cream,                                                                   \n     flour}               => {whole milk} 0.001728521          1 0.001728521 3.913649    17\n[5] {butter,                                                                               \n     soft cheese,                                                                          \n     domestic eggs}       => {whole milk} 0.001016777          1 0.001016777 3.913649    10\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip collapse=\"false\" title=\"Impactos práticos\"}\nNote que o whole milk aparece em quase todos os consequentes. \nFaz sentido gastar verba de marketing recomendando leite para quem já está comprando itens de café da manhã? Provavelmente não, ele já levaria o leite de qualquer forma.\n:::\n\n### Top 5: As Regras de \"Impulso\" (Alto Lift) {.unnumbered}\n\nAgora, vamos extrair as cinco primeiras regras com base no lift mais alto. \nEle nos diz quantas vezes o item B é mais provável de ser comprado quando o item A é comprado do que se eles fossem comprados independentemente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspect(head(rules, n = 5, by = \"lift\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    lhs                        rhs                   support confidence    coverage      lift count\n[1] {liquor,                                                                                       \n     red/blush wine}        => {bottled beer}    0.001931876  0.9047619 0.002135231 11.235269    19\n[2] {citrus fruit,                                                                                 \n     other vegetables,                                                                             \n     soda,                                                                                         \n     fruit/vegetable juice} => {root vegetables} 0.001016777  0.9090909 0.001118454  8.340400    10\n[3] {tropical fruit,                                                                               \n     other vegetables,                                                                             \n     whole milk,                                                                                   \n     yogurt,                                                                                       \n     oil}                   => {root vegetables} 0.001016777  0.9090909 0.001118454  8.340400    10\n[4] {citrus fruit,                                                                                 \n     grapes,                                                                                       \n     fruit/vegetable juice} => {tropical fruit}  0.001118454  0.8461538 0.001321810  8.063879    11\n[5] {other vegetables,                                                                             \n     whole milk,                                                                                   \n     yogurt,                                                                                       \n     rice}                  => {root vegetables} 0.001321810  0.8666667 0.001525165  7.951182    13\n```\n\n\n:::\n:::\n\n\nAqui o cenário muda. O Lift de 11.24 para a regra {liquor, red/blush wine} => {bottled beer} indica uma oportunidade de cross-selling fortíssima que não é óbvia para quem olha apenas o volume de vendas isolado.\n\nA segunda regra mostra que a compra de \"citrus fruit\", \"other vegetables\", \"soda\" e \"fruit/vegetable juice\" está 8.34 vezes mais associada à compra de \"root vegetables\" do que se fosse uma compra independente.\nE assim, sucessivamente.\n\n## Aplicação Prática: \"Operação Cerveja\"\n\nImagine que o estoque de `bottled beer` está alto. Onde devemos atuar?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filtrando regras onde a cerveja é o alvo\nregras_cerveja <- subset(rules, subset = rhs %in% \"bottled beer\")\ninspect(sort(regras_cerveja, by = \"lift\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    lhs                         rhs            support     confidence\n[1] {liquor, red/blush wine} => {bottled beer} 0.001931876 0.9047619 \n    coverage    lift     count\n[1] 0.002135231 11.23527 19   \n```\n\n\n:::\n:::\n\n\nIdentificamos que clientes que compram licor e vinhos têm uma probabilidade de 90.4% de comprar cerveja de garrafa (um comportamento de \"abastecimento de adega\").\nPortanto, uma ação recomendada seria: Em vez de dar desconto na cerveja para todo o mercado, crie um cupom de desconto em cervejas artesanais impresso no verso da nota fiscal apenas para quem comprar vinhos ou licores.\n\n\n<!-- Esse resultado mostra uma regra de associação onde a compra conjunta de \"liquor\" e \"red/blush wine\" (à esquerda, `lhs`) está associada à compra de \"bottled beer\" (à direita, `rhs`).  -->\n<!-- Neste caso, o suporte é de aproximadamente 0.19%, o que significa que cerca de 0.19% de todas as transações incluem \"liquor\", \"red/blush wine\" e \"bottled beer\". -->\n<!-- A confiança é de cerca de 90.48%, o que sugere uma forte associação entre esses itens. -->\n<!-- O  lift é de aproximadamente 11.24, o que significa que a compra de \"liquor\" e \"red/blush wine\" aumenta a probabilidade de compra de \"bottled beer\" em cerca de 11.24 vezes, em comparação com a situação em que essas compras são independentes. -->\n\n<!-- Se fossemos fazer uma ação de divulgação de uma \"bottled beer\", qual seria? -->\n\n<!-- > Uma proporção significativa (aproximadamente 90.5%) dos consumidores que compram licor e vinho vermelho/branco também compram \"bottled beer\". Portanto, seria vantajoso direcionar campanhas publicitárias para esse grupo demográfico, destacando a disponibilidade e a qualidade da \"bottled beer\" em relação aos produtos relacionados, como licores e vinhos. -->\n\n\n### Conclusão\n\nA análise de regras de associação através do algoritmo *apriori* nos permite compreender melhor o comportamento do consumidor e tomar decisões informadas para otimizar as estratégias de marketing. \n\n\nA análise de associação nos permite compreender melhor o comportamento do consumidor. Entretanto, pode servir também para provocar novos comportamentos nos clientes:\n\n- **Suporte Baixo + Lift Alto**: Oportunidade de criar novos hábitos em nichos rentáveis.\n\n- **Suporte Alto + Confiança Alta**: Itens \"âncora\". Não precisam de promoção, mas devem estar localizados no fundo da loja para o cliente percorrer outros corredores.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}